sudo: false
language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - hhvm-nightly

install:
  - composer install

before_script:
  - mysql -e 'create database PeachySQL;'

matrix:
  allow_failures:
    - php: hhvm
    - php: hhvm-nightly
