dist: xenial
language: php

php:
  - 7.1
  - 7.2
  - 7.3

services:
  - mysql

install:
  - composer install

before_script:
  - mysql -u root -e 'create database PeachySQL;'

script:
  - vendor/bin/phpunit
