language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

before_script:
  - travis_retry composer self-update
  - travis_retry composer install
  - mysql -e 'create database PeachySQL;'

script: phpunit

matrix:
  allow_failures:
    - php: hhvm
    - php: hhvm-nightly
