language: php

php:
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

install:
  - composer install

before_script:
  - mysql -e 'create database PeachySQL;'

script: phpunit

matrix:
  allow_failures:
    - php: hhvm-nightly
