language: php
sudo: required
dist: trusty
group: edge

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm-3.12
  - hhvm-nightly

addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

install:
  - composer install

before_script:
  - mysql -u root -e 'create database PeachySQL;'

script:
  - vendor/bin/phpunit

matrix:
  allow_failures:
    - php: hhvm-nightly
